package com.tomppi.enderslicer.calibration

import com.tomppi.enderslicer.model.SlicerSettings

/**
 * Tracks whether the currently loaded model was generated by the calibration
 * builder. The effective settings are created only for slicing; the saved
 * printer/profile settings are never mutated.
 */
internal object CalibrationSliceState {
    @Volatile
    private var active = false

    @Volatile
    private var requiresFirmwareRetraction = false

    fun activate(retraction: Boolean) {
        requiresFirmwareRetraction = retraction
        active = true
    }

    fun clear() {
        active = false
        requiresFirmwareRetraction = false
    }

    fun effective(settings: SlicerSettings): SlicerSettings = settings.forCalibrationSlice(
        active = active,
        requiresFirmwareRetraction = requiresFirmwareRetraction,
    )
}

/**
 * Calibration parts deliberately contain bridges and controlled overhangs.
 * Generated support material would invalidate the comparison, so these
 * overrides are applied only to the calibration slice and are not persisted.
 */
internal fun SlicerSettings.forCalibrationSlice(
    active: Boolean,
    requiresFirmwareRetraction: Boolean,
): SlicerSettings {
    if (!active) return this
    val forcedKeys = buildSet {
        addAll(overriddenSettingKeys)
        add(SlicerSettings.Keys.SUPPORTS_ENABLED)
        add(SlicerSettings.Keys.SUPPORT_INTERFACE_ENABLED)
        if (requiresFirmwareRetraction) add(SlicerSettings.Keys.FIRMWARE_RETRACTION)
    }
    return copy(
        supportsEnabled = false,
        supportInterfaceEnabled = false,
        firmwareRetraction = firmwareRetraction || requiresFirmwareRetraction,
        overriddenSettingKeys = forcedKeys,
    )
}
