package com.tomppi.enderslicer.engine

import android.content.Context
import android.content.res.AssetManager
import com.tomppi.enderslicer.model.PrinterDefinition
import com.tomppi.enderslicer.model.PrusaSliceSettings
import com.tomppi.enderslicer.model.SlicerSettings
import com.tomppi.enderslicer.model.withSettings
import java.io.File
import java.time.Instant
import java.util.UUID
import java.util.concurrent.TimeUnit
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runInterruptible

/**
 * Runs the bundled PrusaSlicer 2.9.6 console for Android ARM64.
 *
 * The console is packaged as a native library ("libprusa_slicer_exec.so" in the
 * APK's arm64-v8a jniLibs, executed directly). It consumes a self-contained
 * .ini generated by [PrusaConfigWriter] plus the bundled resources directory
 * (passed via --datadir), and emits PrusaSlicer-dialect G-code.
 */
class PrusaEngineRunner(private val context: Context) {

    data class SliceResult(
        val artifactId: String,
        val gcodeFile: File,
        val baseGcodeFile: File,
        val logFile: File,
        val elapsedMilliseconds: Long,
        val estimatedPrintSeconds: Int?,
        val layerPreview: GcodeLayerPreview?,
        val layerEvents: List<LayerEvent>,
    )

    class SliceException(
        message: String,
        val logFile: File,
        cause: Throwable? = null,
    ) : Exception(message, cause)

    private data class Workspace(
        val id: String,
        val directory: File,
        val output: File = File(directory, "output.gcode"),
        val model: File = File(directory, "model.stl"),
        val config: File = File(directory, "prusa-config.ini"),
    )

    private val nativeDirectory = File(context.applicationInfo.nativeLibraryDir)
    private val executable = File(nativeDirectory, ENGINE_LIBRARY_NAME)
    private val publisher = SliceArtifactPublisher(File(context.filesDir, "slice-results"))
    private val datadir = File(context.filesDir, "prusa/datadir")

    fun isAvailable(): Boolean = executable.isFile && executable.length() > 0L

    fun status(): String = when {
        !executable.exists() -> "PrusaSlicer 2.9.6 ARM64 is not packaged in this APK"
        !executable.isFile -> "PrusaSlicer package path is invalid"
        executable.length() == 0L -> "PrusaSlicer package is empty"
        else -> "PrusaSlicer 2.9.6 ARM64 ready"
    }

    fun releaseArtifact(id: String) = publisher.release(id)

    /**
     * Extracts the bundled PrusaSlicer resources next to the config dir on first
     * use. Returns true when the resources are present and complete.
     */
    fun prepareResources(): Boolean {
        val marker = File(datadir, ".resources-version")
        if (marker.isFile && marker.readText().trim() == RESOURCES_VERSION) {
            return File(datadir, "resources").isDirectory
        }
        val resources = File(datadir, "resources")
        if (resources.exists()) resources.deleteRecursively()
        resources.mkdirs()
        copyAssetDir(context.assets, "prusa/resources", resources)
        File(datadir, "cache").mkdirs()
        marker.writeText(RESOURCES_VERSION)
        return File(datadir, "resources/profiles").isDirectory
    }

    suspend fun slice(
        modelFile: File,
        printer: PrinterDefinition,
        settings: PrusaSliceSettings,
        machineSettings: SlicerSettings,
        startGcode: String,
        endGcode: String,
        onProgress: (Int) -> Unit = {},
    ): SliceResult = runInterruptible(Dispatchers.IO) {
        sliceBlocking(modelFile, printer, settings, machineSettings, startGcode, endGcode, onProgress)
    }

    private fun sliceBlocking(
        modelFile: File,
        printer: PrinterDefinition,
        settings: PrusaSliceSettings,
        machineSettings: SlicerSettings,
        startGcode: String,
        endGcode: String,
        onProgress: (Int) -> Unit,
    ): SliceResult {
        require(isAvailable()) { status() }
        require(modelFile.isFile && modelFile.length() > 0L) { "The imported STL is no longer available" }
        if (!prepareResources()) {
            throw IllegalStateException("PrusaSlicer resources are not packaged in this APK")
        }

        val workspace = createWorkspace()
        val log = requestLog(workspace.id)
        val started = System.nanoTime()
        val effectivePrinter = effectiveMachine(printer, machineSettings)
        val printerEnvelope = PrinterEnvelope.from(printer.withSettings(machineSettings))

        try {
            writeInitialLog(log, workspace.id, modelFile, printer, settings, startGcode, endGcode, datadir)

            modelFile.copyTo(workspace.model, overwrite = false)
            val config = PrusaConfigWriter.write(workspace.config, settings, effectivePrinter, startGcode, endGcode)

            val command = listOf(
                executable.absolutePath,
                "--datadir", datadir.absolutePath,
                "--load", config.absolutePath,
                "--export-gcode",
                "-o", workspace.output.absolutePath,
                workspace.model.absolutePath,
            )
            appendLog(log, "\nPrusaSlicer command:\n" + command.joinToString(" ") + "\n")

            val processBuilder = ProcessBuilder(command)
                .directory(workspace.directory)
                .redirectErrorStream(true)
                .apply {
                    environment()["LD_LIBRARY_PATH"] = nativeDirectory.absolutePath
                    environment()["TMPDIR"] = workspace.directory.absolutePath
                    environment()["HOME"] = context.filesDir.absolutePath
                }

            val exitCode = runWithProgress(processBuilder, log, onProgress)

            if (exitCode != 0) {
                throw SliceException(
                    "PrusaSlicer failed with exit code $exitCode. Export the error log for full details.",
                    log,
                )
            }
            validateOutput(workspace.output, log)
            throwIfInterrupted()

            val transport = "prusa-ini"
            val summary = GcodeSanitizer.validateAndRepair(
                file = workspace.output,
                settingsTransport = transport,
                printerEnvelope = printerEnvelope,
            )
            val prusaEstimateSeconds = parsePrusaEstimateSeconds(workspace.output) ?: summary.estimatedSeconds
            val preview = runCatching {
                GcodeLayerPreviewParser.parse(workspace.output, GcodeDialect.PRUSA)
            }.getOrNull()

            val artifact = publisher.publish(
                id = workspace.id,
                gcodeSource = workspace.output,
                baseGcodeSource = workspace.output,
                printerEnvelope = printerEnvelope,
            )
            val elapsed = TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - started)
            appendResultLog(log, artifact, summary, preview, elapsed)
            updateLatestLog(log)
            return SliceResult(
                artifactId = artifact.id,
                gcodeFile = artifact.gcodeFile,
                baseGcodeFile = artifact.baseGcodeFile,
                logFile = log,
                elapsedMilliseconds = elapsed,
                estimatedPrintSeconds = prusaEstimateSeconds,
                layerPreview = preview,
                layerEvents = emptyList(),
            )
        } catch (error: InterruptedException) {
            appendLog(log, "\n--- EnderSlicer cancellation ---\nFinished: " + Instant.now() + "\nThe PrusaSlicer request was cancelled and reaped.\n")
            updateLatestLog(log)
            throw error
        } catch (error: Throwable) {
            appendLog(log, "\n--- EnderSlicer failure ---\nFinished: " + Instant.now() + "\n" + error.stackTraceToString() + "\n")
            updateLatestLog(log)
            if (error is SliceException) throw error
            throw SliceException(error.message ?: "PrusaSlicer failed before slicing started", log, error)
        } finally {
            workspace.directory.deleteRecursively()
        }
    }

    /**
     * Starts the process, streams merged output into [log] while parsing
     * PrusaSlicer progress lines ("NN => stage") into [onProgress], and applies
     * the same timeout/kill semantics as the Cura path.
     */
    private fun runWithProgress(
        processBuilder: ProcessBuilder,
        log: File,
        onProgress: (Int) -> Unit,
    ): Int {
        val process = processBuilder.start()
        val logSink = log.bufferedWriter()
        val readerThread = Thread {
            try {
                process.inputStream.bufferedReader().forEachLine { line ->
                    if (line.isNotBlank()) {
                        logSink.appendLine(line)
                        logSink.flush()
                    }
                    progressFrom(line)?.let { percent -> onProgress(percent.coerceIn(0, 100)) }
                }
            } catch (_: Exception) {
            } finally {
                runCatching { logSink.close() }
            }
        }
        readerThread.isDaemon = true
        readerThread.start()
        return try {
            if (!process.waitFor(SLICE_TIMEOUT_MINUTES, TimeUnit.MINUTES)) {
                process.destroy()
                if (!process.waitFor(SHUTDOWN_GRACE_MILLIS, TimeUnit.MILLISECONDS)) {
                    process.destroyForcibly()
                }
                throw InterruptedException("PrusaSlicer timed out after $SLICE_TIMEOUT_MINUTES minutes")
            }
            process.exitValue()
        } finally {
            readerThread.join(2000L)
        }
    }

    /** Parses "; estimated printing time (normal mode) = 22m 46s" (or "4h 10m 3s"). */
    private fun parsePrusaEstimateSeconds(file: File): Int? {
        file.bufferedReader().useLines { lines ->
            for (line in lines) {
                if (!line.startsWith("; estimated printing time")) continue
                val value = line.substringAfter('=').trim()
                val pattern = Regex("""(?:(d+)h)?s*(?:(d+)m)?s*(?:(d+)s)?""")
                val match = pattern.find(value) ?: return 0
                val hours = match.groupValues[1].ifEmpty { "0" }.toInt()
                val minutes = match.groupValues[2].ifEmpty { "0" }.toInt()
                val seconds = match.groupValues[3].ifEmpty { "0" }.toInt()
                return hours * 3600 + minutes * 60 + seconds
            }
        }
        return null
    }

    private fun validateOutput(file: File, log: File) {
        if (!file.isFile || file.length() < MINIMUM_GCODE_BYTES) {
            throw SliceException("PrusaSlicer finished without producing a valid G-code file. Export the error log for details.", log)
        }
        val header = file.bufferedReader().use { reader ->
            buildString {
                repeat(20) {
                    val line = reader.readLine() ?: return@repeat
                    appendLine(line)
                }
            }
        }
        if (header.isBlank() || !header.contains("PrusaSlicer")) {
            throw SliceException("The engine output did not contain a PrusaSlicer G-code header. Export the error log for details.", log)
        }
    }

    /** Overlays the user-edited machine values (same ones the Cura path honors). */
    private fun effectiveMachine(printer: PrinterDefinition, settings: SlicerSettings): PrinterDefinition =
        printer.copy(
            widthMm = settings.machineWidthMm,
            depthMm = settings.machineDepthMm,
            heightMm = settings.machineHeightMm,
            originAtCenter = settings.originAtCenter,
            heatedBed = settings.heatedBed,
            gcodeFlavor = settings.gcodeFlavor,
            nozzleSizeMm = settings.nozzleSizeMm,
            filamentDiameterMm = settings.filamentDiameterMm,
            extruders = settings.enabledExtruderCount,
        )

    private fun createWorkspace(): Workspace {
        val id = "prusa-${System.currentTimeMillis()}-${UUID.randomUUID()}"
        val root = File(context.cacheDir, "prusaengine/requests").apply {
            check(mkdirs() || isDirectory) { "Unable to create the PrusaSlicer request directory" }
        }
        val cutoff = System.currentTimeMillis() - STALE_WORKSPACE_AGE_MILLIS
        root.listFiles().orEmpty()
            .filter { it.isDirectory && it.lastModified() in 1 until cutoff }
            .forEach(File::deleteRecursively)
        val directory = File(root, id)
        check(directory.mkdir()) { "Unable to create an isolated PrusaSlicer workspace" }
        return Workspace(id, directory)
    }

    private fun requestLog(id: String): File = File(context.filesDir, "logs/prusaengine-$id.log").apply {
        parentFile?.mkdirs()
    }

    private fun writeInitialLog(
        log: File,
        id: String,
        model: File,
        printer: PrinterDefinition,
        settings: PrusaSliceSettings,
        startGcode: String,
        endGcode: String,
        datadir: File,
    ) {
        log.writeText(
            buildString {
                appendLine("EnderSlicer PrusaSlicer diagnostic log")
                appendLine("Executable: " + executable.absolutePath)
                appendLine("Datadir: " + datadir.absolutePath)
                appendLine("Model: " + model.absolutePath)
                appendLine("Printer: " + printer.name + " (" + printer.widthMm + "x" + printer.depthMm + "mm, nozzle " + printer.nozzleSizeMm + "mm)")
                appendLine("Layer height: " + settings.layerHeightMm + "mm")
                appendLine("Perimeters: " + settings.perimeters + " · Fill: " + settings.fillDensityPercent + "% " + settings.fillPattern)
                appendLine("Start G-code (" + startGcode.length + " bytes)")
                appendLine("End G-code (" + endGcode.length + " bytes)")
                appendLine("Started: " + Instant.now())
            },
        )
    }

    private fun appendResultLog(
        log: File,
        artifact: SliceArtifactPublisher.PublishedArtifact,
        summary: GcodeSanitizer.Summary,
        preview: GcodeLayerPreview?,
        elapsedMillis: Long,
    ) {
        appendLog(
            log,
            buildString {
                appendLine("\n--- PrusaSlicer result ---")
                appendLine("Artifact: " + artifact.id)
                appendLine("G-code: " + artifact.gcodeFile.absolutePath + " (" + artifact.gcodeFile.length() + " bytes)")
                appendLine("Estimated print time (s): " + summary.estimatedSeconds)
                appendLine("Layer preview: " + if (preview != null) preview.layers.size.toString() + " layers" else "unavailable")
                appendLine("Elapsed: " + elapsedMillis + "ms")
            },
        )
    }

    private fun appendLog(log: File, text: String) {
        runCatching { log.appendText(text) }
    }

    private fun updateLatestLog(log: File) {
        runCatching {
            File(context.filesDir, "logs/latest-prusaengine.log").writeText(log.readText())
        }
    }

    private fun throwIfInterrupted() {
        if (Thread.currentThread().isInterrupted) throw InterruptedException("PrusaSlicer slicing was cancelled")
    }

    private fun copyAssetDir(assets: AssetManager, from: String, destination: File) {
        val children = runCatching { assets.list(from) }.getOrNull() ?: emptyArray()
        if (children.isEmpty()) {
            try {
                assets.open(from).use { input ->
                    destination.outputStream().use { output -> input.copyTo(output) }
                }
            } catch (_: Exception) {
                // Empty directories within the asset tree; ignore.
            }
            return
        }
        for (child in children) {
            val source = "$from/$child"
            val target = File(destination, child)
            val nested = runCatching { assets.list(source) }.getOrNull()
            if (nested.isNullOrEmpty()) {
                target.parentFile?.mkdirs()
                assets.open(source).use { input ->
                    target.outputStream().use { output -> input.copyTo(output) }
                }
            } else {
                target.mkdirs()
                copyAssetDir(assets, source, target)
            }
        }
    }

    companion object {
        /** Accepts "10 => Processing triangulated mesh" style lines. */
        internal fun progressFrom(line: String): Int? {
            val trimmed = line.trimStart()
            val marker = trimmed.indexOf("=>")
            if (marker <= 0) return null
            return trimmed.substring(0, marker).trim().toIntOrNull()
        }

        const val ENGINE_LIBRARY_NAME = "libprusa_slicer_exec.so"
        private const val RESOURCES_VERSION = "prusaslicer-2.9.6-resources-v1"
        private const val SLICE_TIMEOUT_MINUTES = 60L
        private const val SHUTDOWN_GRACE_MILLIS = 3000L
        private const val STALE_WORKSPACE_AGE_MILLIS = 24L * 60 * 60 * 1000
        private const val MINIMUM_GCODE_BYTES = 256L
    }
}
